/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as AuthenticatedAbonnementRouteImport } from './routes/_authenticated/abonnement'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'
import { Route as AuthenticatedAideRouteImport } from './routes/_authenticated/aide'
import { Route as AuthenticatedAmisRouteImport } from './routes/_authenticated/amis'
import { Route as AuthenticatedCadeauxRouteImport } from './routes/_authenticated/cadeaux'
import { Route as AuthenticatedCarteRouteImport } from './routes/_authenticated/carte'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedFavorisRouteImport } from './routes/_authenticated/favoris'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedRecompensesRouteImport } from './routes/_authenticated/recompenses'
import { Route as CommercesMerchantIdRouteImport } from './routes/commerces.$merchantId'
import { Route as OffresOfferIdRouteImport } from './routes/offres.$offerId'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as ProAuthRouteImport } from './routes/pro.auth'
import { Route as ProContactRouteImport } from './routes/pro.contact'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAccesRouteImport } from './routes/_authenticated/admin.acces'
import { Route as AuthenticatedAdminCadeauxRouteImport } from './routes/_authenticated/admin.cadeaux'
import { Route as AuthenticatedAdminCommercesRouteImport } from './routes/_authenticated/admin.commerces'
import { Route as AuthenticatedAdminFraudeRouteImport } from './routes/_authenticated/admin.fraude'
import { Route as AuthenticatedAdminOffresRouteImport } from './routes/_authenticated/admin.offres'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin.parametres'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedEspaceProIndexRouteImport } from './routes/_authenticated/espace-pro.index'
import { Route as AuthenticatedEspaceProEquipeRouteImport } from './routes/_authenticated/espace-pro.equipe'
import { Route as AuthenticatedEspaceProInscriptionRouteImport } from './routes/_authenticated/espace-pro.inscription'
import { Route as AuthenticatedEspaceProOffresRouteImport } from './routes/_authenticated/espace-pro.offres'
import { Route as AuthenticatedEspaceProScannerRouteImport } from './routes/_authenticated/espace-pro.scanner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbonnementRoute = AuthenticatedAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAideRoute = AuthenticatedAideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmisRoute = AuthenticatedAmisRouteImport.update({
  id: '/amis',
  path: '/amis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadeauxRoute = AuthenticatedCadeauxRouteImport.update({
  id: '/cadeaux',
  path: '/cadeaux',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteRoute = AuthenticatedCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavorisRoute = AuthenticatedFavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecompensesRoute =
  AuthenticatedRecompensesRouteImport.update({
    id: '/recompenses',
    path: '/recompenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CommercesMerchantIdRoute = CommercesMerchantIdRouteImport.update({
  id: '/commerces/$merchantId',
  path: '/commerces/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresOfferIdRoute = OffresOfferIdRouteImport.update({
  id: '/offres/$offerId',
  path: '/offres/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProAuthRoute = ProAuthRouteImport.update({
  id: '/pro/auth',
  path: '/pro/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProContactRoute = ProContactRouteImport.update({
  id: '/pro/contact',
  path: '/pro/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAccesRoute = AuthenticatedAdminAccesRouteImport.update({
  id: '/admin/acces',
  path: '/admin/acces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCadeauxRoute =
  AuthenticatedAdminCadeauxRouteImport.update({
    id: '/admin/cadeaux',
    path: '/admin/cadeaux',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCommercesRoute =
  AuthenticatedAdminCommercesRouteImport.update({
    id: '/admin/commerces',
    path: '/admin/commerces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFraudeRoute =
  AuthenticatedAdminFraudeRouteImport.update({
    id: '/admin/fraude',
    path: '/admin/fraude',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOffresRoute =
  AuthenticatedAdminOffresRouteImport.update({
    id: '/admin/offres',
    path: '/admin/offres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/admin/parametres',
    path: '/admin/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceProIndexRoute =
  AuthenticatedEspaceProIndexRouteImport.update({
    id: '/espace-pro/',
    path: '/espace-pro/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceProEquipeRoute =
  AuthenticatedEspaceProEquipeRouteImport.update({
    id: '/espace-pro/equipe',
    path: '/espace-pro/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceProInscriptionRoute =
  AuthenticatedEspaceProInscriptionRouteImport.update({
    id: '/espace-pro/inscription',
    path: '/espace-pro/inscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceProOffresRoute =
  AuthenticatedEspaceProOffresRouteImport.update({
    id: '/espace-pro/offres',
    path: '/espace-pro/offres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceProScannerRoute =
  AuthenticatedEspaceProScannerRouteImport.update({
    id: '/espace-pro/scanner',
    path: '/espace-pro/scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/explorer': typeof ExplorerRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/aide': typeof AuthenticatedAideRoute
  '/amis': typeof AuthenticatedAmisRoute
  '/cadeaux': typeof AuthenticatedCadeauxRoute
  '/carte': typeof AuthenticatedCarteRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/favoris': typeof AuthenticatedFavorisRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/recompenses': typeof AuthenticatedRecompensesRoute
  '/commerces/$merchantId': typeof CommercesMerchantIdRoute
  '/offres/$offerId': typeof OffresOfferIdRoute
  '/pro/auth': typeof ProAuthRoute
  '/pro/contact': typeof ProContactRoute
  '/pro/': typeof ProIndexRoute
  '/admin/acces': typeof AuthenticatedAdminAccesRoute
  '/admin/cadeaux': typeof AuthenticatedAdminCadeauxRoute
  '/admin/commerces': typeof AuthenticatedAdminCommercesRoute
  '/admin/fraude': typeof AuthenticatedAdminFraudeRoute
  '/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/espace-pro/equipe': typeof AuthenticatedEspaceProEquipeRoute
  '/espace-pro/inscription': typeof AuthenticatedEspaceProInscriptionRoute
  '/espace-pro/offres': typeof AuthenticatedEspaceProOffresRoute
  '/espace-pro/scanner': typeof AuthenticatedEspaceProScannerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/espace-pro/': typeof AuthenticatedEspaceProIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/explorer': typeof ExplorerRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/abonnement': typeof AuthenticatedAbonnementRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/aide': typeof AuthenticatedAideRoute
  '/amis': typeof AuthenticatedAmisRoute
  '/cadeaux': typeof AuthenticatedCadeauxRoute
  '/carte': typeof AuthenticatedCarteRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/favoris': typeof AuthenticatedFavorisRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/recompenses': typeof AuthenticatedRecompensesRoute
  '/commerces/$merchantId': typeof CommercesMerchantIdRoute
  '/offres/$offerId': typeof OffresOfferIdRoute
  '/pro/auth': typeof ProAuthRoute
  '/pro/contact': typeof ProContactRoute
  '/pro': typeof ProIndexRoute
  '/admin/acces': typeof AuthenticatedAdminAccesRoute
  '/admin/cadeaux': typeof AuthenticatedAdminCadeauxRoute
  '/admin/commerces': typeof AuthenticatedAdminCommercesRoute
  '/admin/fraude': typeof AuthenticatedAdminFraudeRoute
  '/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/espace-pro/equipe': typeof AuthenticatedEspaceProEquipeRoute
  '/espace-pro/inscription': typeof AuthenticatedEspaceProInscriptionRoute
  '/espace-pro/offres': typeof AuthenticatedEspaceProOffresRoute
  '/espace-pro/scanner': typeof AuthenticatedEspaceProScannerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/espace-pro': typeof AuthenticatedEspaceProIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/explorer': typeof ExplorerRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/_authenticated/abonnement': typeof AuthenticatedAbonnementRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/aide': typeof AuthenticatedAideRoute
  '/_authenticated/amis': typeof AuthenticatedAmisRoute
  '/_authenticated/cadeaux': typeof AuthenticatedCadeauxRoute
  '/_authenticated/carte': typeof AuthenticatedCarteRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/favoris': typeof AuthenticatedFavorisRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/recompenses': typeof AuthenticatedRecompensesRoute
  '/commerces/$merchantId': typeof CommercesMerchantIdRoute
  '/offres/$offerId': typeof OffresOfferIdRoute
  '/pro/auth': typeof ProAuthRoute
  '/pro/contact': typeof ProContactRoute
  '/pro/': typeof ProIndexRoute
  '/_authenticated/admin/acces': typeof AuthenticatedAdminAccesRoute
  '/_authenticated/admin/cadeaux': typeof AuthenticatedAdminCadeauxRoute
  '/_authenticated/admin/commerces': typeof AuthenticatedAdminCommercesRoute
  '/_authenticated/admin/fraude': typeof AuthenticatedAdminFraudeRoute
  '/_authenticated/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/espace-pro/equipe': typeof AuthenticatedEspaceProEquipeRoute
  '/_authenticated/espace-pro/inscription': typeof AuthenticatedEspaceProInscriptionRoute
  '/_authenticated/espace-pro/offres': typeof AuthenticatedEspaceProOffresRoute
  '/_authenticated/espace-pro/scanner': typeof AuthenticatedEspaceProScannerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/espace-pro/': typeof AuthenticatedEspaceProIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/confirmation'
    | '/explorer'
    | '/faq'
    | '/mentions-legales'
    | '/abonnement'
    | '/accueil'
    | '/aide'
    | '/amis'
    | '/cadeaux'
    | '/carte'
    | '/compte'
    | '/favoris'
    | '/notifications'
    | '/profil'
    | '/recompenses'
    | '/commerces/$merchantId'
    | '/offres/$offerId'
    | '/pro/auth'
    | '/pro/contact'
    | '/pro/'
    | '/admin/acces'
    | '/admin/cadeaux'
    | '/admin/commerces'
    | '/admin/fraude'
    | '/admin/offres'
    | '/admin/parametres'
    | '/admin/support'
    | '/espace-pro/equipe'
    | '/espace-pro/inscription'
    | '/espace-pro/offres'
    | '/espace-pro/scanner'
    | '/admin/'
    | '/espace-pro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/confirmation'
    | '/explorer'
    | '/faq'
    | '/mentions-legales'
    | '/abonnement'
    | '/accueil'
    | '/aide'
    | '/amis'
    | '/cadeaux'
    | '/carte'
    | '/compte'
    | '/favoris'
    | '/notifications'
    | '/profil'
    | '/recompenses'
    | '/commerces/$merchantId'
    | '/offres/$offerId'
    | '/pro/auth'
    | '/pro/contact'
    | '/pro'
    | '/admin/acces'
    | '/admin/cadeaux'
    | '/admin/commerces'
    | '/admin/fraude'
    | '/admin/offres'
    | '/admin/parametres'
    | '/admin/support'
    | '/espace-pro/equipe'
    | '/espace-pro/inscription'
    | '/espace-pro/offres'
    | '/espace-pro/scanner'
    | '/admin'
    | '/espace-pro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/confirmation'
    | '/explorer'
    | '/faq'
    | '/mentions-legales'
    | '/_authenticated/abonnement'
    | '/_authenticated/accueil'
    | '/_authenticated/aide'
    | '/_authenticated/amis'
    | '/_authenticated/cadeaux'
    | '/_authenticated/carte'
    | '/_authenticated/compte'
    | '/_authenticated/favoris'
    | '/_authenticated/notifications'
    | '/_authenticated/profil'
    | '/_authenticated/recompenses'
    | '/commerces/$merchantId'
    | '/offres/$offerId'
    | '/pro/auth'
    | '/pro/contact'
    | '/pro/'
    | '/_authenticated/admin/acces'
    | '/_authenticated/admin/cadeaux'
    | '/_authenticated/admin/commerces'
    | '/_authenticated/admin/fraude'
    | '/_authenticated/admin/offres'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/support'
    | '/_authenticated/espace-pro/equipe'
    | '/_authenticated/espace-pro/inscription'
    | '/_authenticated/espace-pro/offres'
    | '/_authenticated/espace-pro/scanner'
    | '/_authenticated/admin/'
    | '/_authenticated/espace-pro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ExplorerRoute: typeof ExplorerRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  CommercesMerchantIdRoute: typeof CommercesMerchantIdRoute
  OffresOfferIdRoute: typeof OffresOfferIdRoute
  ProAuthRoute: typeof ProAuthRoute
  ProContactRoute: typeof ProContactRoute
  ProIndexRoute: typeof ProIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abonnement': {
      id: '/_authenticated/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AuthenticatedAbonnementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aide': {
      id: '/_authenticated/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AuthenticatedAideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amis': {
      id: '/_authenticated/amis'
      path: '/amis'
      fullPath: '/amis'
      preLoaderRoute: typeof AuthenticatedAmisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadeaux': {
      id: '/_authenticated/cadeaux'
      path: '/cadeaux'
      fullPath: '/cadeaux'
      preLoaderRoute: typeof AuthenticatedCadeauxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carte': {
      id: '/_authenticated/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof AuthenticatedCarteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoris': {
      id: '/_authenticated/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof AuthenticatedFavorisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recompenses': {
      id: '/_authenticated/recompenses'
      path: '/recompenses'
      fullPath: '/recompenses'
      preLoaderRoute: typeof AuthenticatedRecompensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/commerces/$merchantId': {
      id: '/commerces/$merchantId'
      path: '/commerces/$merchantId'
      fullPath: '/commerces/$merchantId'
      preLoaderRoute: typeof CommercesMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$offerId': {
      id: '/offres/$offerId'
      path: '/offres/$offerId'
      fullPath: '/offres/$offerId'
      preLoaderRoute: typeof OffresOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/auth': {
      id: '/pro/auth'
      path: '/pro/auth'
      fullPath: '/pro/auth'
      preLoaderRoute: typeof ProAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/contact': {
      id: '/pro/contact'
      path: '/pro/contact'
      fullPath: '/pro/contact'
      preLoaderRoute: typeof ProContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/acces': {
      id: '/_authenticated/admin/acces'
      path: '/admin/acces'
      fullPath: '/admin/acces'
      preLoaderRoute: typeof AuthenticatedAdminAccesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cadeaux': {
      id: '/_authenticated/admin/cadeaux'
      path: '/admin/cadeaux'
      fullPath: '/admin/cadeaux'
      preLoaderRoute: typeof AuthenticatedAdminCadeauxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/commerces': {
      id: '/_authenticated/admin/commerces'
      path: '/admin/commerces'
      fullPath: '/admin/commerces'
      preLoaderRoute: typeof AuthenticatedAdminCommercesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fraude': {
      id: '/_authenticated/admin/fraude'
      path: '/admin/fraude'
      fullPath: '/admin/fraude'
      preLoaderRoute: typeof AuthenticatedAdminFraudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/offres': {
      id: '/_authenticated/admin/offres'
      path: '/admin/offres'
      fullPath: '/admin/offres'
      preLoaderRoute: typeof AuthenticatedAdminOffresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace-pro/': {
      id: '/_authenticated/espace-pro/'
      path: '/espace-pro'
      fullPath: '/espace-pro/'
      preLoaderRoute: typeof AuthenticatedEspaceProIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace-pro/equipe': {
      id: '/_authenticated/espace-pro/equipe'
      path: '/espace-pro/equipe'
      fullPath: '/espace-pro/equipe'
      preLoaderRoute: typeof AuthenticatedEspaceProEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace-pro/inscription': {
      id: '/_authenticated/espace-pro/inscription'
      path: '/espace-pro/inscription'
      fullPath: '/espace-pro/inscription'
      preLoaderRoute: typeof AuthenticatedEspaceProInscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace-pro/offres': {
      id: '/_authenticated/espace-pro/offres'
      path: '/espace-pro/offres'
      fullPath: '/espace-pro/offres'
      preLoaderRoute: typeof AuthenticatedEspaceProOffresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace-pro/scanner': {
      id: '/_authenticated/espace-pro/scanner'
      path: '/espace-pro/scanner'
      fullPath: '/espace-pro/scanner'
      preLoaderRoute: typeof AuthenticatedEspaceProScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonnementRoute: typeof AuthenticatedAbonnementRoute
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedAideRoute: typeof AuthenticatedAideRoute
  AuthenticatedAmisRoute: typeof AuthenticatedAmisRoute
  AuthenticatedCadeauxRoute: typeof AuthenticatedCadeauxRoute
  AuthenticatedCarteRoute: typeof AuthenticatedCarteRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedFavorisRoute: typeof AuthenticatedFavorisRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRecompensesRoute: typeof AuthenticatedRecompensesRoute
  AuthenticatedAdminAccesRoute: typeof AuthenticatedAdminAccesRoute
  AuthenticatedAdminCadeauxRoute: typeof AuthenticatedAdminCadeauxRoute
  AuthenticatedAdminCommercesRoute: typeof AuthenticatedAdminCommercesRoute
  AuthenticatedAdminFraudeRoute: typeof AuthenticatedAdminFraudeRoute
  AuthenticatedAdminOffresRoute: typeof AuthenticatedAdminOffresRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedEspaceProEquipeRoute: typeof AuthenticatedEspaceProEquipeRoute
  AuthenticatedEspaceProInscriptionRoute: typeof AuthenticatedEspaceProInscriptionRoute
  AuthenticatedEspaceProOffresRoute: typeof AuthenticatedEspaceProOffresRoute
  AuthenticatedEspaceProScannerRoute: typeof AuthenticatedEspaceProScannerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedEspaceProIndexRoute: typeof AuthenticatedEspaceProIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonnementRoute: AuthenticatedAbonnementRoute,
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedAideRoute: AuthenticatedAideRoute,
  AuthenticatedAmisRoute: AuthenticatedAmisRoute,
  AuthenticatedCadeauxRoute: AuthenticatedCadeauxRoute,
  AuthenticatedCarteRoute: AuthenticatedCarteRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedFavorisRoute: AuthenticatedFavorisRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRecompensesRoute: AuthenticatedRecompensesRoute,
  AuthenticatedAdminAccesRoute: AuthenticatedAdminAccesRoute,
  AuthenticatedAdminCadeauxRoute: AuthenticatedAdminCadeauxRoute,
  AuthenticatedAdminCommercesRoute: AuthenticatedAdminCommercesRoute,
  AuthenticatedAdminFraudeRoute: AuthenticatedAdminFraudeRoute,
  AuthenticatedAdminOffresRoute: AuthenticatedAdminOffresRoute,
  AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedEspaceProEquipeRoute: AuthenticatedEspaceProEquipeRoute,
  AuthenticatedEspaceProInscriptionRoute:
    AuthenticatedEspaceProInscriptionRoute,
  AuthenticatedEspaceProOffresRoute: AuthenticatedEspaceProOffresRoute,
  AuthenticatedEspaceProScannerRoute: AuthenticatedEspaceProScannerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedEspaceProIndexRoute: AuthenticatedEspaceProIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfirmationRoute: ConfirmationRoute,
  ExplorerRoute: ExplorerRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  CommercesMerchantIdRoute: CommercesMerchantIdRoute,
  OffresOfferIdRoute: OffresOfferIdRoute,
  ProAuthRoute: ProAuthRoute,
  ProContactRoute: ProContactRoute,
  ProIndexRoute: ProIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
